apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: demo
  ports:
    - name: demo1234
      protocol: TCP
      port: 1234
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

