apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  namespace: exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-img
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: pingpong
          image: enayetee/pingpong
          env:
            - name: FILE_DIR
              value: /usr/src/app/files
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: USER
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PASS
          volumeMounts:
            - name: shared-img
              mountPath: /usr/src/app/files

