apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
  namespace: exercise
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
